spring:
  profiles:
#    active: tx
    active: nontx
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password: password
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  kafka:
    bootstrap-servers: localhost:9092
    consumer.properties:
      max.poll.records: 50
      max.poll.interval.ms: 600000 # 10min

logging:
  level:
    org.springframework.transaction: TRACE
    org.springframework.kafka.transaction: TRACE
    org.springframework.kafka.producer: TRACE
    org.springframework.kafka.core: TRACE
