spring.kafka:
  bootstrap-servers: 192.168.2.240:9092
  consumer.properties:
    max.poll.records: 50
    max.poll.interval.ms: 600000 # 10min

spring.cloud:
  function:
    definition: "ackSendPerson"
  stream:
    kafka:
      binder:
        replication-factor: 1
        min-partition-count: 1
        configuration:
          isolation:
            level: read_committed
        transaction:
          transaction-id-prefix: sandbox-tx-
          producer.configuration:
            retries: 5
            acks: all
    bindings:
      sendPerson-out-0:
        destination: demo.tx.out.send-person
      ackSendPerson-in-0:
        destination: demo.tx.out.send-person
        group: ackPersonGroup

logging:
  level:
    org.springframework.transaction: TRACE
    org.springframework.kafka.transaction: TRACE
    org.springframework.kafka.producer: TRACE
    org.springframework.kafka.core: TRACE
